# Generated by Django 4.2.16 on 2024-10-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdata',
            name='lectures',
            field=models.FileField(null=True, upload_to='resources/'),
        ),
    ]
