# Generated by Django 4.2.16 on 2024-10-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_classdata_lectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdata',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googleclss', to='authz.googleclass'),
        ),
    ]
